spring:
  data:
    mongodb:
      auto-index-creation: false
      protocol: ${MONGODB_PROTOCOL:mongodb}
      username: ${MONGODB_USERNAME:myUsername}
      password: ${MONGODB_PASSWORD:myPassword}
      hostname: ${MONGODB_HOSTNAME:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:admin}
 